image: maven:3.6.3-openjdk-11
 
variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true
    -DdeployAtEnd=true

before_script:
  - >-
    echo " ------------------------------- Global > Before Script
    ------------------------- ------"
  - echo $CI_COMMIT_BRANCH
  
stages:
  - build_deploy
 
dbfront11:
  image: node:17
  stage: build_deploy
  cache:
    paths:
      - node_modules/
  only:
    - main
  before_script:
    - ls -la
    - apk update && apk add openssh-client bash
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo $USER_PASS > /dev/null 2>&1
    - echo "$USER_PASS" | tr -d '\r' | ssh-add - > /dev/null 
    #- ssh-add <(echo "${USER_PASS}" | base64 -d)
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H $SERVER_IPf1 >> ~/.ssh/known_hosts
  script:
    - cd front11/
    - npm install
    - CI=false npm run build 
    - ls
    # just two lines for deployment
    #- ssh-add <(echo "$USER_PASS")
    
    - scp -v -r build/ $USER_NAME@$SERVER_IPf1:/var/www/html 
    
    
#22