pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                cd frontTwo/
				BUILD_DIR=build/
				ls -la

				echo "----------------------DIRECTORY VERIFICATION---------------------------"

				if [ -d $BUILD_DIR ]
				then
					rm -r build/
					echo "----------------BUILD DIRECTORY HAS BEEN SUCCESFULLY DELETED------------"
				else
					echo "-------------------DIRECTORY DOES NOT EXISTS-------------------------"
				fi

				echo "-------------------STARTING AUTENTICATION PROCESS------------------------"

				#apk update && apk add openssh-client bash
				mkdir -p ~/.ssh
				eval $(ssh-agent -s)
				echo $USER_PASS > /dev/null 2>&1
				echo "$USER_PASS" | tr -d '\r' | ssh-add - > /dev/null 
				touch ~/.ssh/config
				echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
				ssh-keyscan -H $SERVER_IPf2 >> ~/.ssh/known_host

				echo "-------------------------BUILDING FRONT 2----------------------------------"

				npm install
				CI=false npm run build 
				ls

				echo "------------------------DEPLOYING FRONT 2---------------------------------"
				ssh-add <(echo "$USER_PASS")
				scp -v -r build/ $USER_NAME@$SERVER_IPf2:/var/www/html
            }
        }
    }
}